kind: Service
apiVersion: v1
metadata:
  name: kube-service
spec:
  type: NodePort
  selector:
    app: kube-deployment
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30562
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-deployment
  labels:
    app: kube-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kube-deployment
      track: stable
  template:
    metadata:
      labels:
        app: kube-deployment
        track: stable
    spec:
      containers:
      - name: kube-addressbook
        image: erashish01/myaddressapp
